/// Firebase configuration options for QuickQueue Pro.
///
/// Auto-generated by FlutterFire CLI for project: streetvendors-1cd02
/// Re-run `flutterfire configure` to update these values.
library;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  /// Returns the correct [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─────────────────────────────────────────────────────────────
  // Firebase app configurations per platform
  // ─────────────────────────────────────────────────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYEp6FVT-EgqARxyI-sfYt4xmPCLakob0',
    appId: '1:999681334311:web:e396f7d7f94d3b13974202',
    messagingSenderId: '999681334311',
    projectId: 'streetvendors-1cd02',
    authDomain: 'streetvendors-1cd02.firebaseapp.com',
    storageBucket: 'streetvendors-1cd02.firebasestorage.app',
    measurementId: 'G-HQV1WR1M9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_DCG7DPJR-hYeJWkEhF89s-vQBed-Qk',
    appId: '1:999681334311:android:198de64910db9862974202',
    messagingSenderId: '999681334311',
    projectId: 'streetvendors-1cd02',
    storageBucket: 'streetvendors-1cd02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVtnqnqS0Gozdlk63cR5RA_9_E1t1ukZE',
    appId: '1:999681334311:ios:d60dd0d998f719ed974202',
    messagingSenderId: '999681334311',
    projectId: 'streetvendors-1cd02',
    storageBucket: 'streetvendors-1cd02.firebasestorage.app',
    iosBundleId: 'com.example.vendorcodesimwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVtnqnqS0Gozdlk63cR5RA_9_E1t1ukZE',
    appId: '1:999681334311:ios:d60dd0d998f719ed974202',
    messagingSenderId: '999681334311',
    projectId: 'streetvendors-1cd02',
    storageBucket: 'streetvendors-1cd02.firebasestorage.app',
    iosBundleId: 'com.example.vendorcodesimwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYEp6FVT-EgqARxyI-sfYt4xmPCLakob0',
    appId: '1:999681334311:web:e396f7d7f94d3b13974202',
    messagingSenderId: '999681334311',
    projectId: 'streetvendors-1cd02',
    authDomain: 'streetvendors-1cd02.firebaseapp.com',
    storageBucket: 'streetvendors-1cd02.firebasestorage.app',
  );
}