// File generated by FlutterFire CLI, then secured with flutter_dotenv.
// DO NOT commit this file with real API keys.
// Real keys must live in .env (which is gitignored).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Returns the [FirebaseOptions] for the current platform, reading all
/// sensitive values from the environment loaded by flutter_dotenv.
///
/// Usage:
/// ```dart
/// await dotenv.load(fileName: '.env');
/// await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
/// ```
class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported by this app.');
      default:
        throw UnsupportedError('Unknown platform.');
    }
  }

  // ── Helpers ────────────────────────────────────────────────
  /// Reads a required key from the loaded .env; throws if missing.
  static String _env(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      throw StateError(
        'Missing environment variable "$key". '
        'Check your .env file and make sure dotenv.load() was called first.',
      );
    }
    return value;
  }

  // ── Web ────────────────────────────────────────────────────
  static FirebaseOptions get web => FirebaseOptions(
        apiKey:            _env('FIREBASE_WEB_API_KEY'),
        appId:             _env('FIREBASE_WEB_APP_ID'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID'),
        projectId:         _env('FIREBASE_PROJECT_ID'),
        authDomain:        _env('FIREBASE_AUTH_DOMAIN'),
        storageBucket:     _env('FIREBASE_STORAGE_BUCKET'),
        measurementId:     dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'],
      );

  // ── Android ────────────────────────────────────────────────
  static FirebaseOptions get android => FirebaseOptions(
        apiKey:            _env('FIREBASE_ANDROID_API_KEY'),
        appId:             _env('FIREBASE_ANDROID_APP_ID'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID'),
        projectId:         _env('FIREBASE_PROJECT_ID'),
        storageBucket:     _env('FIREBASE_STORAGE_BUCKET'),
      );

  // ── iOS ────────────────────────────────────────────────────
  static FirebaseOptions get ios => FirebaseOptions(
        apiKey:            _env('FIREBASE_IOS_API_KEY'),
        appId:             _env('FIREBASE_IOS_APP_ID'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID'),
        projectId:         _env('FIREBASE_PROJECT_ID'),
        storageBucket:     _env('FIREBASE_STORAGE_BUCKET'),
        iosClientId:       dotenv.env['FIREBASE_IOS_CLIENT_ID'],
        iosBundleId:       _env('FIREBASE_IOS_BUNDLE_ID'),
      );

  // ── macOS ──────────────────────────────────────────────────
  static FirebaseOptions get macos => FirebaseOptions(
        apiKey:            _env('FIREBASE_MACOS_API_KEY'),
        appId:             _env('FIREBASE_MACOS_APP_ID'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID'),
        projectId:         _env('FIREBASE_PROJECT_ID'),
        storageBucket:     _env('FIREBASE_STORAGE_BUCKET'),
        iosClientId:       dotenv.env['FIREBASE_MACOS_CLIENT_ID'],
        iosBundleId:       _env('FIREBASE_MACOS_BUNDLE_ID'),
      );

  // ── Windows ────────────────────────────────────────────────
  static FirebaseOptions get windows => FirebaseOptions(
        apiKey:            _env('FIREBASE_WINDOWS_API_KEY'),
        appId:             _env('FIREBASE_WINDOWS_APP_ID'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID'),
        projectId:         _env('FIREBASE_PROJECT_ID'),
        authDomain:        _env('FIREBASE_AUTH_DOMAIN'),
        storageBucket:     _env('FIREBASE_STORAGE_BUCKET'),
      );
}
